<?php

/**
 * @file
 * Prepares for hat logging.
 */

/**
 * Implelemts hook_ten_million_with_a_hat_also_do_these_things().
 */
function prepare_for_hat_logging_ten_million_with_a_hat_also_do_these_things() {
  // Before we even start, store the old values and set custom ones.
  $exclude_bots = variable_get('islandora_usage_stats_exclude_bots', 1);
  $exclude_ips = variable_get('islandora_usage_stats_ip_list', 'localhost 127.0.0.1');
  $cooldown_time = variable_get('islandora_usage_stats_cooldown_seconds', 300);
  variable_set('islandora_usage_stats_exclude_bots', 0);
  variable_set('islandora_usage_stats_ip_list', '4.4.4.4');
  variable_set('islandora_usage_stats_cooldown_seconds', -1);
  return array(
    // Before the batch, inform of the old variables in the event that the batch
    // fails and after_batch hooks don't run.
    array(
      'when' => 'before_batch',
      'message' => "Islandora Usage Stats variables have been overwritten for the duration of this batch. In the event " .
      "of a failure, the variables will have to be manually reset to their original values (" .
      "islandora_usage_stats_exclude_bots: '$exclude_bots', " .
      "islandora_usage_stats_ip_list: '$exclude_ips', " .
      "islandora_usage_stats_cooldown_seconds: '$cooldown_time').",
    ),
    // Just use variable_set to replace the old values.
    array(
      'when' => 'after_batch',
      'callback' => 'variable_set',
      'args' => array('islandora_usage_stats_exclude_bots', $exclude_bots),
      'message' => "The islandora_usage_stats_exclude_bots variable has been re-written to '$exclude_bots'.",
    ),
    array(
      'when' => 'after_batch',
      'callback' => 'variable_set',
      'args' => array('islandora_usage_stats_ip_list', $exclude_ips),
      'message' => "The islandora_usage_stats_ip_list variable has been re-written to '$exclude_ips'.",
    ),
    array(
      'when' => 'after_batch',
      'callback' => 'variable_set',
      'args' => array('islandora_usage_stats_cooldown_seconds', $cooldown_time),
      'message' => "The islandora_usage_stats_cooldown_seconds variable has been re-written to '$cooldown_time'.",
    ),
  );
}
