<?php

/**
 * @file
 * Implements hook to log views for each new hat.
 */

/**
 * Implements hook_ten_million_with_a_hat_also_do_these_things().
 */
function log_hat_views_ten_million_with_a_hat_also_do_these_things() {
  return array(
    array(
      'callback' => 'log_hat_views_log_hat_view',
    ),
  );
}

/**
 * Logs a view on a hat.
 *
 * @param AbstractObject $object
 *   The object to log a view for.
 */
function log_hat_views_log_hat_view(AbstractObject $object) {
  $tracker = new IslandoraUsageStats($object->id);
  $tracker->logObjectView();
}
