<?php

/**
 * @file
 * Implements hook to add each new hat to a compound object.
 */

/**
 * Implements hook_ten_million_with_a_hat_also_do_these_things().
 */
function hats_in_a_compound_hat_ten_million_with_a_hat_also_do_these_things() {
  global $user;
  $tuque = islandora_get_tuque_connection();
  $compound = $tuque->repository->constructObject('compound');
  $compound->label = "Compound hat";
  $compound->owner = $user->name;
  $compound->models = (array) 'islandora:compoundCModel';
  $tuque->repository->ingestObject($compound);
  cache_set('hats_in_a_compound_hat_id', $compound->id);
  return array(
    'Add the hat to a compound!' => array(
      'callback' => 'islandora_compound_object_add_parent',
      'file' => array(
        'type' => 'inc',
        'module' => 'islandora_compound_object',
        'path' => 'includes/manage.form',
      ),
      'args' => array($compound->id),
    ),
  );
}

/**
 * Implements hook_ten_million_with_a_hat_also_say_these_things().
 */
function hats_in_a_compound_hat_ten_million_with_a_hat_also_say_these_things() {
  $compound = cache_get('hats_in_a_compound_hat_id');
  cache_clear_all('hats_in_a_compound_hat_id', 'cache');
  return array(
    array(
      'type' => 'before_batch',
      'message' => "Adding all objects to compound object $compound.",
    ),
    array(
      'type' => 'after_batch',
      'message' => "Note: all ingested objects can be found as members of the compound object $compound.",
    ),
  );
}
