<?php

/**
 * @file
 * Adds a second random content model to ingested objects.
 */

/**
 * Implements hook_ten_million_with_a_hat_also_do_these_things().
 */
function add_second_hat_model_ten_million_with_a_hat_also_do_these_things() {
  module_load_include('inc', 'islandora', 'includes/utilities');
  $models = array();
  foreach (islandora_get_content_models() as $model) {
    $models[] = $model['pid'];
  }
  return array(
    array(
      'callback' => 'add_second_hat_model_apply_random_hat',
      'when' => 'between_ingests',
      'args' => array($models),
    ),
  );
}

/**
 * Applies a random second hat to the object.
 *
 * @var AbstractObject $object
 *   The object to apply the hat to.
 * @var array $models
 *   An array of content model PIDs to choose from.
 */

function add_second_hat_model_apply_random_hat(AbstractObject $object, array $models) {
  if (count($object->models) === 2) {
    $new_model = ten_million_with_a_hat_get_random_array_member(array_diff($models, $object->models));
    $object->relationships->add(FEDORA_MODEL_URI, 'hasModel', $new_model);
    return "Added second content model {$new_model} to {$object->id}.";
  }
  $count = count($object->models);
  return "Object had $count models";
}
