<?php

/**
 * @file
 * Implements hook to log downloads for each new hat.
 */

/**
 * Implements hook_ten_million_with_a_hat_also_do_these_things().
 */
function log_hat_downloads_ten_million_with_a_hat_also_do_these_things() {
  return array(
    array(
      'callback' => 'log_hat_downloads_log_hat_download',
      // Make sure this happens after any OBJs are created.
      'weight' => 52,
      'when' => 'between_ingests',
    ),
  );
}

/**
 * Logs a download on a hat.
 *
 * @param AbstractObject $object
 *   The object to log a download for.
 */
function log_hat_downloads_log_hat_download(AbstractObject $object) {
  if ($object['OBJ']) {
    module_load_include('inc', 'islandora_usage_stats', 'includes/utilities');
    $num_downloads = mt_rand(1, 9);
    for ($i = 0; $i <= $num_downloads; $i++) {
      islandora_usage_stats_log_datastream_download($object->id, 'OBJ');
      sleep(1);
    }
    $num_downloads++;
    return "Logged $num_downloads downloads on {$object->id}.";
  }
}
